export const menuItems = [
  {
    id: 1,
    category: "Espresso",
    name: "Classic Espresso",
    description: "Rich, bold and aromatic single-shot espresso.",
    price: 199,
    rating: 4.9,
    image: "/images/menu/espresso.png",
  },
  {
    id: 2,
    category: "Latte",
    name: "Caramel Latte",
    description: "Smooth espresso blended with creamy caramel milk.",
    price: 279,
    rating: 4.8,
    image: "/images/menu/latte.png",
  },
  {
    id: 3,
    category: "Mocha",
    name: "Dark Mocha",
    description: "Chocolate infused espresso topped with foam.",
    price: 299,
    rating: 4.9,
    image: "/images/menu/mocha.png",
  },
  {
    id: 4,
    category: "Cold Brew",
    name: "Vanilla Cold Brew",
    description: "Slow-steeped coffee with vanilla cream.",
    price: 329,
    rating: 5.0,
    image: "/images/menu/coldbrew.png",
  },
  {
    id: 5,
    category: "Dessert",
    name: "Blueberry Cheesecake",
    description: "Creamy cheesecake with fresh blueberries.",
    price: 349,
    rating: 4.9,
    image: "/images/menu/cheesecake.png",
  },
  {
    id: 6,
    category: "Dessert",
    name: "Chocolate Brownie",
    description: "Warm chocolate brownie with rich cocoa.",
    price: 249,
    rating: 4.8,
    image: "/images/menu/brownie.png",
  },
];